### ISSUE TITLE
Add support for subjects that are missing instances of some conditions

### ISSUE THREAD

**Issue by boydmeredith** [mwaskom/lyman#57]

**Comment by iancballard** [comment]
Empty conditions is kind of a nightmare situation. Last I checked FSL itself doesn't handle this situation intuitively. I would run these subjects without that condition specified in the model at all, and if you had multiple runs, toss the runs with empty conditions for that particular contrast from the 2nd level analysis. This is obviously a pain. Michael might disagree, but for lyman I would recommend making a second project with these subjects with symbolic links to only the runs missing conditions, run these through the 2nd-level (FYI the level nomenclature is different in FSL and SPM), and manually pull the outputs back into the main lyman workflow.

**Comment by mwaskom** [comment]
Lyman handles the case where subjects have some runs without any instances of a condition fine. The problem here arises where some subjects have no instances of a particular condition in *any* run. The current solution is  to make multiple model files for different groups of subjects, but that is still a pain. I think it's possible to catch the error that gets raised when a condition is completely missing and write out some dummy files to let the processing continue; this is just a stub issue to remind me to do that next time I'm working on the lyman code.

**Comment by iancballard** [comment]
Just thought I'd ask before running a big job: When using run_group, will there be a problem if some subjects dont have a contrast? (Because they had no instances of a condition in any run and I made separate model files for them)

**Comment by mwaskom** [comment]
Yes, the group level model will look for fixed-effects output by subject and so there will be an issue if those files don't exist: https://github.com/mwaskom/lyman/blob/master/scripts/run_group.py#L77

**Comment by iancballard** [comment]
do you have a recommendation for a hack so that run_group.py only runs runs a subset of the contrasts, and then I could feed it the appropriate subject lists. Or is the problem hopeless for the time being?

**Comment by mwaskom** [comment]
You already have the separate model files right?

**Comment by iancballard** [comment]
Yeah that part was fine. The situation I’m facing is:

Contrast A is not defined in some subjects, and so there are two model files for each group of subjects

Contrast B has no problem with any of the subjects, and is defined within both model files

I’d like to run group analysis where contrast A is calculated based off some subjects and contrast B is calculated based off all subjects.

If I’m understanding right, run_group with all subjects will fail because contrast A isnt define for all subjects, and hence I cant look at contrast B with the full subject group.

**Comment by mwaskom** [comment]
I might be confused, but why can't you just run the model that doesn't have contrast A defined to get the results for contrast B?

**Comment by iancballard** [comment]
oh that’s smart. Thanks and sorry my brain is still weary from pride
