### ISSUE TITLE
missing runs

### ISSUE THREAD

**Issue by iancballard** [mwaskom/lyman#62]
Is there support in Lyman for if a subject is missing a run of data? (From, for example, a rather buggy mux implementation)

**Comment by mwaskom** [comment]
Yes that should work fine.

**Comment by mwaskom** [comment]
Make sure to double check though...

**Comment by iancballard** [comment]
Works fine, but FYI for others, lyman renames runs. So if run 2 is missing, lyman will rename run3 to run2 and you should make sure your design file reflects this.

**Comment by mwaskom** [comment]
Another option would be to run the preproc and model code on all data but then delete the model outputs for the crappy runs, which then won't get picked up at the registration stage.

This assumes that the mux issues aren't going to result in a model that crashes film_gls (e.g. because you end up with a ton of artifact volumes)

**Comment by iancballard** [comment]
For mux runs with reconstructions problems, the artefacts do crash film. If you’ve collected enough calibration scans throughout the experiment, this shouldn’t be too much of a problem. However, our scanner also has the nice feature of randomly not saving an entire run of mux data every so often (fix forthcoming)
