### ISSUE TITLE
calculate_sat_point could be updated to account for surface stats

### ISSUE THREAD

**Issue by sgagnon** [mwaskom/lyman#93]
When regspace=='fsaverage' the stat_temp file is not in z units; since the max z-value is calculated via calculate_sat_point() before any conversion to z, I think the units should probably be adjusted before determining max(3.71, np.percentile(data,98)) in this function?

**Comment by mwaskom** [comment]
Steph.

**Comment by mwaskom** [comment]
I need more context for what you're talking about.

**Comment by sgagnon** [comment]
Oops, I meant to say this was in surface_snapshots.py.

When the group analyses are done on the surface, the function calculate_sat_point() doesn't adjust for the fact that the stat file is in -10log(p). I think this ends up being roughly equivalent to z-stats, but might be a little off unless the data is converted to z-stats before determining if the 98th percentile is greater than 3.71.

**Comment by sgagnon** [comment]
I can take a shot at fixing this if you want, but just wanted to double check that it's actually an issue (even if super minor) and I'm not missing something.

**Comment by mwaskom** [comment]
That's just a default point for the upper range of the colormap (i.e. the point at which the colormap saturates). It's true that the corresponding p value will be slightly different (0.00019 for a -log10(p) value and 0.0001 for a z statistic) but it should not really matter. Colormaps for zstats and -log10(p) values are already incommensurate because the nonlinearities are different.

In any case, surface_snapshots is just a way of quickly generating some summary files, not anything you should use to make figures for a publication.

**Comment by mwaskom** [comment]
Closing as there is no more `surface_snapshots.py`
